version: '3.4'

x-common-variables: &common-variables
  HSELING_API_ENDPOINT: http://hse-api-web:8080/api/

services:
  hse-api-web:
    build:
      context: .
      dockerfile: hseling-api-chukchi-type/Dockerfile
    ports:
      - "5000:5000"

  hse-web-web:
    build:
      context: .
      dockerfile: hseling-web-chukchi-type/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - hse-api-web
    environment: *common-variables
